Repository boostcampwm-2021/iOS02-SanTa, pull requests merged in 2021-11, with the labels that each got.

#7 [Feat] 폴더 구조 정의
  SanTa/SanTa.xcodeproj/project.pbxproj
  SanTa/SanTa/Application/AppDelegate.swift
  SanTa/SanTa/Application/SceneDelegate.swift
  SanTa/SanTa/Application/TabBarController.swift
  SanTa/SanTa/MapScene/MapViewController.swift
  SanTa/SanTa/MapScene/MapViewModel.swift
  SanTa/SanTa/MapScene/MapViewRepository.swift
  SanTa/SanTa/MapScene/MapViewUseCase.swift
  SanTa/SanTa/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  SanTa/SanTa/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  SanTa/SanTa/Resources/Assets.xcassets/Contents.json
  SanTa/SanTa/Resources/Base.lproj/LaunchScreen.storyboard
  SanTa/SanTa/Resources/Info.plist
  SanTa/SanTa/Resources/SanTa.xcdatamodeld/.xccurrentversion
  SanTa/SanTa/Resources/SanTa.xcdatamodeld/SanTa.xcdatamodel/contents
  SanTa/SanTa/SanTa.xcdatamodeld/SanTa.xcdatamodel/contents
Labels: Feature

#9 [Feat] Coordinator Pattern 적용
  SanTa/SanTa.xcodeproj/project.pbxproj
  SanTa/SanTa/Application/AppCoordinator.swift
  SanTa/SanTa/Application/SceneDelegate.swift
  SanTa/SanTa/Application/TabBarController.swift
  SanTa/SanTa/MapScene/MapViewController.swift
  SanTa/SanTa/MapScene/MapViewCoordinator.swift
  SanTa/SanTa/MountainListScene/MountainListViewController.swift
  SanTa/SanTa/MountainListScene/MountainListViewCoordinator.swift
  SanTa/SanTa/RecordingScene/RecordingViewController.swift
  SanTa/SanTa/RecordingScene/RecordingViewCoordinator.swift
  SanTa/SanTa/ResultScene/ResultViewController.swift
  SanTa/SanTa/ResultScene/ResultViewCoordinator.swift
  SanTa/SanTa/SettingsScene/SettingsViewController.swift
  SanTa/SanTa/SettingsScene/SettingsViewCoordinator.swift
Labels: Feature

#13 [Feat] 산 목록화면 View 구현
  SanTa/SanTa.xcodeproj/project.pbxproj
  SanTa/SanTa/MountainListScene/MountainCell.swift
  SanTa/SanTa/MountainListScene/MountainListViewController.swift
  SanTa/SanTa/MountainListScene/MountainListViewCoordinator.swift
Labels: Feature

#20 [Feat] MapView Layout 및 마커 구현
  SanTa/SanTa.xcodeproj/project.pbxproj
  SanTa/SanTa.xcodeproj/xcshareddata/xcschemes/SanTa.xcscheme
  SanTa/SanTa/MapScene/ClusterAnnotationView.swift
  SanTa/SanTa/MapScene/MapViewController.swift
  SanTa/SanTa/MapScene/MountainAnnotationView.swift
  SanTa/SanTa/Resources/Info.plist
Labels: Feature, MapKit, CoreMotion

#26 [Fix] 클러스터링이 적용되지 않는 버그 수정
  SanTa/SanTa/MapScene/MapViewController.swift
Labels: bug

#28 [Feat] 거리, 걸음, 고도, 시간 확인 기능
  SanTa/SanTa.xcodeproj/project.pbxproj
  SanTa/SanTa/RecordingScene/RecordingViewController+Extension.swift
  SanTa/SanTa/RecordingScene/RecordingViewController.swift
  SanTa/SanTa/RecordingScene/RecordingViewModel.swift
  SanTa/SanTa/Resources/Info.plist
Labels: Feature, CoreMotion, CoreLocation

#31 [Feat] 설정화면 View 구현
  SanTa/SanTa.xcodeproj/project.pbxproj
  SanTa/SanTa/MountainListScene/MountainListViewController.swift
  SanTa/SanTa/SettingsScene/MapOptionCell.swift
  SanTa/SanTa/SettingsScene/PaddingLabel.swift
  SanTa/SanTa/SettingsScene/SettingsViewController.swift
  SanTa/SanTa/SettingsScene/ToggleOptionCell.swift
Labels: Feature, Layout

#32 [Feat] 종이비행기 버튼, 나침반, 축척 구현
  SanTa/SanTa/MapScene/MapViewController.swift
Labels: Feature, MapKit, CoreLocation

#34 [Fix] Merge 과정에서 중복된 코드 제거
  SanTa/SanTa/MapScene/MapViewController.swift
Labels: bug

#45 [Feat] 지도에 전국 산 마커 표시
  SanTa/SanTa.xcodeproj/project.pbxproj
  SanTa/SanTa/Entities/MountainEntity.swift
  SanTa/SanTa/MapScene/MapViewController.swift
  SanTa/SanTa/MapScene/MapViewCoordinator.swift
  SanTa/SanTa/MapScene/MapViewModel.swift
  SanTa/SanTa/MapScene/MapViewRepository.swift
  SanTa/SanTa/MapScene/MapViewUseCase.swift
  SanTa/SanTa/MapScene/MountainAnnotation.swift
  SanTa/SanTa/Persistences/MountainExtractor.swift
  SanTa/SanTa/Resources/Assets.xcassets/MountainsWithLocation.dataset/Contents.json
  SanTa/SanTa/Resources/Assets.xcassets/MountainsWithLocation.dataset/MountainsWithLocation.json
Labels: Feature

#51 [Feat] 시작 화면에서 측정 화면으로 이동 구현
  SanTa/SanTa/MapScene/MapViewController.swift
  SanTa/SanTa/MapScene/MapViewCoordinator.swift
  SanTa/SanTa/RecordingScene/RecordingViewController.swift
  SanTa/SanTa/RecordingScene/RecordingViewCoordinator.swift
Labels: Feature

#52 [Feat] 측정 기록 데이터 CoreData 저장 구현
  SanTa/SanTa.xcodeproj/project.pbxproj
  SanTa/SanTa/Persistences/CoreDataStorage.swift
  SanTa/SanTa/RecordingScene/CoreDataRecordStorage.swift
  SanTa/SanTa/RecordingScene/Record.swift
  SanTa/SanTa/RecordingScene/RecordRepository.swift
  SanTa/SanTa/RecordingScene/RecordingUseCase.swift
  SanTa/SanTa/Resources/SanTa.xcdatamodeld/SanTa.xcdatamodel/contents
Labels: Feature, CoreData

#54 [Fix] Merge 이후 실행 불가한 Xcode에러 해결
  SanTa/SanTa/MapScene/MapViewCoordinator.swift
  SanTa/SanTa/Resources/SanTa.xcdatamodeld/SanTa.xcdatamodel/contents
Labels: bug

#56 [Refactor] MapViewController 리펙토링
  SanTa/SanTa/MapScene/MapViewController.swift
Labels: Refactor

#61 [Fix] 종이 비행기 버튼이 나타나지 않는 버그 수정
  SanTa/SanTa/MapScene/MapViewController.swift
Labels: bug

#64 [Feature] 마커 터치시 말풍선 추가, JSON 파일 정확도 개선
  SanTa/SanTa/MapScene/MapViewController.swift
  SanTa/SanTa/MapScene/MountainAnnotationView.swift
  SanTa/SanTa/Resources/Assets.xcassets/MountainsWithLocation.dataset/Contents.json
  SanTa/SanTa/Resources/Assets.xcassets/MountainsWithLocation.dataset/MountainsWithLocation2.json
Labels: Feature, Refactor

#67 [Fix] Core Data Entity Inverse 지정
  SanTa/SanTa/Resources/SanTa.xcdatamodeld/SanTa.xcdatamodel/contents
Labels: bug, CoreData

#65 [Feature] RecordingViewModel 구조 개선 및 CoreData 저장
  SanTa/SanTa/MapScene/MapViewCoordinator.swift
  SanTa/SanTa/RecordingScene/RecordingUseCase.swift
  SanTa/SanTa/RecordingScene/RecordingViewController.swift
  SanTa/SanTa/RecordingScene/RecordingViewCoordinator.swift
  SanTa/SanTa/RecordingScene/RecordingViewModel.swift
Labels: Feature, ViewModel, CoreData, Refactor

#72 [Fix] 클러스터링이 정상적으로 작동하지 않는 버그 수정
  SanTa/SanTa/MapScene/MapViewController.swift
Labels: bug

#80 [Fix] 중복된 코드 제거
  SanTa/SanTa/MapScene/MapViewController.swift
Labels: bug

#82 [Refactor] 권한 변경시 Switch문을 이용한 분기 사용
  SanTa/SanTa/MapScene/MapViewController.swift
Labels: Refactor

#86 [Feature] 지도 화면에서 측정 시작 이전에 권한 여부를 확인하기
  SanTa/SanTa/MapScene/MapViewController.swift
Labels: Feature

#90 [Feature] 시작 버튼에 애니메이션 추가
  SanTa/SanTa.xcodeproj/project.pbxproj
  SanTa/SanTa/MapScene/MapViewController.swift
  SanTa/SanTa/MapScene/MapViewCoordinator.swift
  SanTa/SanTa/MapScene/UIImage+Gif.swift
  SanTa/SanTa/RecordingScene/RecordingViewCoordinator.swift
  SanTa/SanTa/Resources/walkingManAnimation.gif
Labels: Feature

#87 [Feature] 설정화면 구현
  SanTa/SanTa.xcodeproj/project.pbxproj
  SanTa/SanTa.xcodeproj/xcshareddata/xcschemes/SanTa.xcscheme
  SanTa/SanTa/Persistences/UserDefaultsStorage.swift
  SanTa/SanTa/SettingsScene/MapOptionCell.swift
  SanTa/SanTa/SettingsScene/Option.swift
  SanTa/SanTa/SettingsScene/Settings.swift
  SanTa/SanTa/SettingsScene/SettingsRepository.swift
  SanTa/SanTa/SettingsScene/SettingsUsecase.swift
  SanTa/SanTa/SettingsScene/SettingsViewController.swift
  SanTa/SanTa/SettingsScene/SettingsViewCoordinator.swift
  SanTa/SanTa/SettingsScene/SettingsViewModel.swift
  SanTa/SanTa/SettingsScene/ToggleOptionCell.swift
  SanTa/SettingsSceneTests/SettingsUsecaseTests.swift
  SanTa/SettingsSceneTests/SettingsViewModelTests.swift
Labels: Feature

#92 [Feature] Recording Background Task 구현
  SanTa/SanTa.xcodeproj/project.pbxproj
  SanTa/SanTa/RecordingScene/CoreDataRecordStorage.swift
  SanTa/SanTa/RecordingScene/Record.swift
  SanTa/SanTa/RecordingScene/RecordingModel.swift
  SanTa/SanTa/RecordingScene/RecordingUseCase.swift
  SanTa/SanTa/Resources/Info.plist
Labels: Feature

#94 [Feature] 산 상세화면 일부 구현 및 코디네이터 수정
  SanTa/SanTa.xcodeproj/project.pbxproj
  SanTa/SanTa/Application/AppCoordinator.swift
  SanTa/SanTa/MapScene/MapViewController.swift
  SanTa/SanTa/MapScene/MapViewCoordinator.swift
  SanTa/SanTa/MapScene/MountainAnnotation.swift
  SanTa/SanTa/MountainDetailScene/MountainDetailModel.swift
  SanTa/SanTa/MountainDetailScene/MountainDetailUseCase.swift
  SanTa/SanTa/MountainDetailScene/MountainDetailViewController.swift
  SanTa/SanTa/MountainDetailScene/MountainDetailViewCoordinator.swift
  SanTa/SanTa/MountainDetailScene/MountainDetailViewModel.swift
  SanTa/SanTa/MountainListScene/MountainListViewCoordinator.swift
  SanTa/SanTa/RecordingScene/RecordingViewCoordinator.swift
  SanTa/SanTa/ResultScene/ResultViewCoordinator.swift
  SanTa/SanTa/SettingsScene/SettingsViewCoordinator.swift
Labels: Feature, Layout, ViewModel, Refactor

#121 [Feature] 산 상세화면 스크롤
  SanTa/SanTa.xcodeproj/project.pbxproj
  SanTa/SanTa/MapScene/MountainAnnotation.swift
  SanTa/SanTa/MountainDetailScene/MountainDetailTableViewCell.swift
  SanTa/SanTa/MountainDetailScene/MountainDetailTitleView.swift
  SanTa/SanTa/MountainDetailScene/MountainDetailUseCase.swift
  SanTa/SanTa/MountainDetailScene/MountainDetailViewController.swift
Labels: Feature

#101 [Feature] 앱 처음 실행 시 UserDefaults 값 세팅
  SanTa/SanTa/Application/AppCoordinator.swift
  SanTa/SanTa/Application/SceneDelegate.swift
  SanTa/SanTa/Persistences/UserDefaultsStorage.swift
  SanTa/SanTa/SettingsScene/SettingsRepository.swift
  SanTa/SanTa/SettingsScene/SettingsUsecase.swift
  SanTa/SanTa/SettingsScene/SettingsViewCoordinator.swift
  SanTa/SettingsSceneTests/SettingsUsecaseTests.swift
Labels: Feature

#110 [Feature] RecordingTitleView 완료
  SanTa/SanTa.xcodeproj/project.pbxproj
  SanTa/SanTa/RecordingScene/RecordingUseCase.swift
  SanTa/SanTa/RecordingScene/RecordingViewController.swift
  SanTa/SanTa/RecordingScene/RecordingViewCoordinator.swift
  SanTa/SanTa/RecordingScene/RecordingViewModel.swift
  SanTa/SanTa/RecordingTitleScene/RecordingTitleViewController.swift
  SanTa/SanTa/RecordingTitleScene/RecordingTitleViewCoordinator.swift
Labels: Feature, Layout

#107 [Fix] 잘못된 self 제거
  SanTa/SanTa/MapScene/MapViewController.swift
Labels: bug

#108 [Refactor] protocol을 이용한 간접참조
  SanTa/SanTa/MapScene/MapViewController.swift
  SanTa/SanTa/MapScene/MapViewCoordinator.swift
Labels: Refactor

#117 [Feature] 지도 형식 변경 기능
  SanTa/SanTa/MapScene/MapViewController.swift
  SanTa/SanTa/MapScene/MapViewCoordinator.swift
  SanTa/SanTa/MapScene/MapViewModel.swift
  SanTa/SanTa/MapScene/MapViewRepository.swift
  SanTa/SanTa/MapScene/MapViewUseCase.swift
Labels: Feature, MapKit

#124 [Fix] Merge 이후 발생한 컴파일 에러 해결
  SanTa/SanTa/MapScene/MapViewCoordinator.swift
  SanTa/SanTa/RecordingScene/RecordingViewCoordinator.swift
  SanTa/SanTa/RecordingTitleScene/RecordingTitleViewCoordinator.swift
Labels: bug

#127 [Refactor] Persistence 주입 구조 수정
  SanTa/SanTa/Application/AppCoordinator.swift
  SanTa/SanTa/MapScene/MapViewCoordinator.swift
  SanTa/SanTa/Persistences/UserDefaultsStorage.swift
  SanTa/SanTa/RecordingScene/RecordingViewCoordinator.swift
  SanTa/SanTa/SettingsScene/SettingsViewCoordinator.swift
Labels: Refactor

#129 [Fix] RecordingView Dismiss 시에 크래쉬 발생 해결
  SanTa/SanTa/RecordingScene/RecordingModel.swift
  SanTa/SanTa/RecordingScene/RecordingUseCase.swift
  SanTa/SanTa/RecordingScene/RecordingViewController.swift
  SanTa/SanTa/RecordingScene/RecordingViewCoordinator.swift
  SanTa/SanTa/RecordingTitleScene/RecordingTitleViewController.swift
  SanTa/SanTa/RecordingTitleScene/RecordingTitleViewCoordinator.swift
Labels: bug

#139 [Refactor] RecordingViewController CoreData 리팩토링 및 저장 실패 이벤트 추가
  SanTa/SanTa/Persistences/CoreDataStorage.swift
  SanTa/SanTa/RecordingScene/CoreDataRecordStorage.swift
  SanTa/SanTa/RecordingScene/Record.swift
  SanTa/SanTa/RecordingScene/RecordRepository.swift
  SanTa/SanTa/RecordingScene/RecordingModel.swift
  SanTa/SanTa/RecordingScene/RecordingUseCase.swift
  SanTa/SanTa/RecordingScene/RecordingViewController+Extension.swift
  SanTa/SanTa/RecordingScene/RecordingViewController.swift
  SanTa/SanTa/RecordingScene/RecordingViewModel.swift
  SanTa/SanTa/Resources/SanTa.xcdatamodeld/SanTa.xcdatamodel/contents
Labels: Feature, CoreData, Refactor

#151 [Feature] 산 목록화면 검색기능 완료
  SanTa/SanTa.xcodeproj/project.pbxproj
  SanTa/SanTa/Application/AppCoordinator.swift
  SanTa/SanTa/Entities/MountainEntity.swift
  SanTa/SanTa/MountainListScene/MountainCell.swift
  SanTa/SanTa/MountainListScene/MountainListViewController.swift
  SanTa/SanTa/MountainListScene/MountainListViewCoordinator.swift
  SanTa/SanTa/MountainListScene/MountainListViewModel.swift
  SanTa/SanTa/MountainListScene/MountainListViewRepository.swift
  SanTa/SanTa/MountainListScene/MountainListViewUseCase.swift
  SanTa/SanTa/RecordingScene/RecordingViewController+Extension.swift
  SanTa/SanTa/RecordingTitleScene/RecordingTitleViewController.swift
  SanTa/SanTa/Resources/Assets.xcassets/RecordingSubViewBackgroundColor.colorset/Contents.json
Labels: Feature, Layout, ViewModel

#154 [Feat] #153 기록 화면 Layout
  SanTa/SanTa/ResultScene/ResultViewController.swift
Labels: Feature, Layout

#155 [Feat] 산 상세화면 스크롤 오류 수정 및 기록 상세화면 뷰
  SanTa/SanTa.xcodeproj/project.pbxproj
  SanTa/SanTa/MountainDetailScene/MountainDetailViewController.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailSmallerInfoView.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailViewController.swift
Labels: Feature, Layout

#156 [Feature] CoreData에서 데이터 Fetch, Model 생성
  SanTa/SanTa.xcodeproj/project.pbxproj
  SanTa/SanTa/Persistences/CoreDataRecordStorage.swift
  SanTa/SanTa/RecordingScene/Record.swift
  SanTa/SanTa/RecordingScene/RecordingModel.swift
  SanTa/SanTa/Resources/SanTa.xcdatamodeld/SanTa.xcdatamodel/contents
  SanTa/SanTa/ResultScene/ResultRepository.swift
  SanTa/SanTa/ResultScene/ResultUseCase.swift
Labels: Feature, CoreData

#157 [Feat] 기록 상세화면 정보창 확대/축소
  SanTa/SanTa.xcodeproj/project.pbxproj
  SanTa/SanTa/ResultDetailScene/ResultDetailLargerInfoView.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailSmallerInfoView.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailViewController 2.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailViewController.swift
Labels: Feature

#164 [Refactor] #163 Record 리펙토링
  SanTa/SanTa/RecordingScene/Record.swift
Labels: Refactor

#165 [Featrue] 측정 화면 중 촬영 된 사진 가져오기
  SanTa/SanTa.xcodeproj/project.pbxproj
  SanTa/SanTa/RecordingPhotoScene/RecordingPhotoCoordinator.swift
  SanTa/SanTa/RecordingPhotoScene/RecordingPhotoViewController.swift
  SanTa/SanTa/RecordingScene/Record.swift
  SanTa/SanTa/RecordingScene/RecordingPhotoModel.swift
  SanTa/SanTa/RecordingScene/RecordingUseCase.swift
  SanTa/SanTa/RecordingScene/RecordingViewController.swift
  SanTa/SanTa/RecordingScene/RecordingViewCoordinator.swift
  SanTa/SanTa/Resources/Info.plist
Labels: Feature, CoreLocation

#183 [Refactor] 고도차 계산 리펙토링
  SanTa/SanTa/RecordingScene/Record.swift
Labels: Refactor

#185 [Refactor] 반복되는 부분 리펙토링
  SanTa/SanTa/ResultScene/RecordsViewCell.swift
  SanTa/SanTa/ResultScene/TotalRecordsViewCell.swift
Labels: Refactor

#188 [Feature] 애니메이션 색상, 버튼 터치 이벤트 변경
  SanTa/SanTa/MapScene/MapViewController.swift
  SanTa/SanTa/MapScene/UIImage+Gif.swift
Labels: Feature

#194 [Feature] 진동 피드백
  SanTa/SanTa/Application/AppCoordinator.swift
  SanTa/SanTa/MapScene/MapViewController.swift
Labels: Feature

#199 [Fix] TabBar DarkMode 대응 및 Personal Color 적용
  SanTa/SanTa/Application/AppCoordinator.swift
Labels: bug

#201 [Refactor] ResultViewController 리펙토링
  SanTa/SanTa/ResultScene/ResultViewController.swift
Labels: Refactor

#202 [Fix] Sticky Header 적용
  SanTa/SanTa/ResultScene/ResultViewController.swift
Labels: bug

#204 [Refactor] 기록 화면에서 DarkMode
  SanTa/SanTa/Resources/Assets.xcassets/RecodingResultCellColor.colorset/Contents.json
  SanTa/SanTa/ResultScene/RecordsViewCell.swift
  SanTa/SanTa/ResultScene/SectionHeaderView.swift
Labels: Refactor

#187 [Featrue] GPS 동작 중 예외처리 완료
  SanTa/SanTa/Persistences/CoreDataRecordStorage.swift
  SanTa/SanTa/RecordingScene/Record.swift
  SanTa/SanTa/RecordingScene/RecordingModel.swift
  SanTa/SanTa/RecordingScene/RecordingPhotoModel.swift
  SanTa/SanTa/RecordingScene/RecordingUseCase.swift
  SanTa/SanTa/RecordingScene/RecordingViewController.swift
  SanTa/SanTa/RecordingScene/RecordingViewModel.swift
  SanTa/SanTa/Resources/SanTa.xcdatamodeld/SanTa.xcdatamodel/contents
  SanTa/SanTa/ResultScene/ResultUseCase.swift
Labels: Feature, ViewModel, CoreLocation

#191 [Refactor] 설정화면 뷰 리펙토링
  SanTa/SanTa/SettingsScene/MapOptionCell.swift
  SanTa/SanTa/SettingsScene/ToggleOptionCell.swift
Labels: Refactor

#197 [Feature] 개별 기록화면 데이터 계산
  SanTa/SanTa.xcodeproj/project.pbxproj
  SanTa/SanTa/MountainDetailScene/MountainDetailCategoryLabel.swift
  SanTa/SanTa/MountainDetailScene/MountainDetailTableViewCell.swift
  SanTa/SanTa/ResultDetailScene/CollectionViewCell.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailLargerInfoView.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailModel.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailUseCase.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailViewModel.swift
  SanTa/SanTa/SettingsScene/PaddingLabel.swift
Labels: Feature

#233 [Feature] 개별 기록화면 상세 정보 ViewModel, 셀 레이아웃
  SanTa/SanTa.xcodeproj/project.pbxproj
  SanTa/SanTa/MountainDetailScene/MountainDetailViewController.swift
  SanTa/SanTa/RecordingScene/Record.swift
  SanTa/SanTa/ResultDetailScene/CollectionViewCell.swift
  SanTa/SanTa/ResultDetailScene/DetailCell.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailCoordinator.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailLargerInfoView.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailModel.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailUseCase.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailViewController.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailViewModel.swift
  SanTa/SanTa/ResultScene/ResultViewController.swift
  SanTa/SanTa/ResultScene/ResultViewCoordinator.swift
Labels: Feature, ViewModel

#208 [Feat] 기록 이름 표시
  SanTa/SanTa/ResultScene/RecordsViewCell.swift
  SanTa/SanTa/ResultScene/ResultViewController.swift
Labels: Feature

#210 [Feature] 기록의 날짜를 구분하여 표기하는 기능
  SanTa/SanTa/ResultScene/ResultViewModel.swift
Labels: Feature

#212 [Fix] 가로모드 통제
  SanTa/SanTa/Application/AppDelegate.swift
Labels: bug

#221 [Refactor] MapScene 리펙토링
  SanTa/SanTa/MapScene/MapViewController.swift
  SanTa/SanTa/MapScene/MapViewCoordinator.swift
  SanTa/SanTa/MapScene/MapViewModel.swift
  SanTa/SanTa/MapScene/MapViewUseCase.swift
Labels: Refactor

#217 [Featrue] RecodingView Voice 기능 및 시간 계산 로직 완료
  SanTa/SanTa/Application/AppDelegate.swift
  SanTa/SanTa/MapScene/MapViewCoordinator.swift
  SanTa/SanTa/Persistences/CoreDataRecordStorage.swift
  SanTa/SanTa/RecordingScene/Record.swift
  SanTa/SanTa/RecordingScene/RecordRepository.swift
  SanTa/SanTa/RecordingScene/RecordingModel.swift
  SanTa/SanTa/RecordingScene/RecordingPhotoModel.swift
  SanTa/SanTa/RecordingScene/RecordingUseCase.swift
  SanTa/SanTa/RecordingScene/RecordingViewController.swift
  SanTa/SanTa/RecordingScene/RecordingViewCoordinator.swift
  SanTa/SanTa/RecordingScene/RecordingViewModel.swift
  SanTa/SanTa/Resources/Info.plist
  SanTa/SanTa/Resources/SanTa.xcdatamodeld/SanTa.xcdatamodel/contents
  SanTa/SanTa/ResultScene/ResultUseCase.swift
Labels: Feature, CoreData, CoreLocation

#224 [Feature] 설정화면 VoiceOver 적용
  SanTa/SanTa/Resources/SanTa.xcdatamodeld/SanTa.xcdatamodel/contents
  SanTa/SanTa/SettingsScene/MapOptionCell.swift
  SanTa/SanTa/SettingsScene/SettingsViewController.swift
  SanTa/SanTa/SettingsScene/ToggleOptionCell.swift
Labels: Feature

#239 [Refactor] 설정화면 리펙토링
  SanTa/SanTa/Persistences/UserDefaultsStorage.swift
  SanTa/SanTa/SettingsScene/Settings.swift
  SanTa/SanTa/SettingsScene/SettingsUsecase.swift
  SanTa/SanTa/SettingsScene/SettingsViewController.swift
  SanTa/SanTa/SettingsScene/SettingsViewModel.swift
Labels: Refactor

#241 [Feature] 기록 상세 화면으로 이동
  SanTa/SanTa.xcodeproj/project.pbxproj
  SanTa/SanTa/MapScene/MapViewCoordinator.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailCoordinator.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailViewController.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailViewCoordinator.swift
  SanTa/SanTa/ResultScene/ResultViewController.swift
  SanTa/SanTa/ResultScene/ResultViewCoordinator.swift
  SanTa/SanTa/ResultScene/ResultViewModel.swift
Labels: Feature

#244 [Refactor] RecordingUseCase TestCode
  SanTa/RecordingSceneTests/RecordingUseCaseTests.swift
  SanTa/SanTa.xcodeproj/project.pbxproj
  SanTa/SanTa.xcodeproj/xcshareddata/xcschemes/SanTa.xcscheme
  SanTa/SanTa/Persistences/CoreDataRecordStorage.swift
  SanTa/SanTa/RecordingScene/RecordRepository.swift
  SanTa/SanTa/RecordingScene/RecordingUseCase.swift
  SanTa/SanTa/RecordingScene/RecordingViewModel.swift
Labels: Refactor

#245 [Feature] MountainList Cell Touch시 Push 동작
  SanTa/SanTa/MountainDetailScene/MountainDetailViewController.swift
  SanTa/SanTa/MountainDetailScene/MountainDetailViewCoordinator.swift
  SanTa/SanTa/MountainListScene/MountainListViewController.swift
  SanTa/SanTa/MountainListScene/MountainListViewCoordinator.swift
Labels: Feature

#249 [Fix] 앱이 기록화면에서 크래시가 나는 버그 해결
  SanTa/SanTa/Resources/Info.plist
Labels: bug

#254 [Feature] 개별 기록화면 정보 ViewModel 수정, 변경 버튼 액션
  SanTa/SanTa/ResultDetailScene/ResultDetailModel.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailSmallerInfoView.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailViewController.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailViewModel.swift
Labels: Feature

#251 [Refactor] MapScene 리펙토링
  SanTa/SanTa/MapScene/MapViewController.swift
  SanTa/SanTa/MapScene/MapViewModel.swift
  SanTa/SanTa/MapScene/MapViewUseCase.swift
Labels: Refactor

#257 [Feature] 기록 삭제 및 제목 변경, 이동 경로 그리기
  SanTa/SanTa.xcodeproj/project.pbxproj
  SanTa/SanTa/MapScene/MapViewController.swift
  SanTa/SanTa/Persistences/CoreDataRecordStorage.swift
  SanTa/SanTa/RecordingScene/Record.swift
  SanTa/SanTa/RecordingScene/RecordingModel.swift
  SanTa/SanTa/RecordingScene/RecordingViewController.swift
  SanTa/SanTa/RecordingTitleScene/RecordingTitleViewController.swift
  SanTa/SanTa/RecordingTitleScene/RecordingTitleViewCoordinator.swift
  SanTa/SanTa/Resources/SanTa.xcdatamodeld/SanTa.xcdatamodel/contents
  SanTa/SanTa/ResultDetailScene/ResultDetailModel.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailRepository.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailUseCase.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailViewController.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailViewCoordinator.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailViewModel.swift
  SanTa/SanTa/ResultScene/ResultUseCase.swift
Labels: Feature

#262 [Feature] 산 상세화면, 시작화면, 측정화면 VoiceOver 적용
  SanTa/SanTa/MapScene/MapViewController.swift
  SanTa/SanTa/MountainDetailScene/MountainDetailViewController.swift
  SanTa/SanTa/RecordingScene/RecordingModel.swift
  SanTa/SanTa/RecordingScene/RecordingViewController+Extension.swift
  SanTa/SanTa/RecordingScene/RecordingViewController.swift
  SanTa/SanTa/RecordingScene/RecordingViewModel.swift
Labels: Feature

#268 [Feat] 장소 등록 화면 레이아웃, 산 이름, 설명, 저장소에 저장하기
  SanTa/SanTa.xcodeproj/project.pbxproj
  SanTa/SanTa/MountainAddingScene/MountainAddingView.swift
  SanTa/SanTa/MountainAddingScene/MountainAddingViewController.swift
  SanTa/SanTa/MountainAddingScene/MountainAddingViewCoordinator.swift
  SanTa/SanTa/MountainAddingScene/MountainAddingViewModel.swift
  SanTa/SanTa/MountainAddingScene/MountainAddingViewRepository.swift
  SanTa/SanTa/MountainAddingScene/MountainAddingViewUseCase.swift
  SanTa/SanTa/Persistences/CoreDataMountainStorage.swift
  SanTa/SanTa/Resources/SanTa.xcdatamodeld/SanTa.xcdatamodel/contents
Labels: Feature, CoreLocation

#269 [Feature] 기록 상세화면 정보창 스와이프
  SanTa/SanTa.xcodeproj/project.pbxproj
  SanTa/SanTa/Application/AppDelegate.swift
  SanTa/SanTa/ResultDetailScene/DetailCell.swift
  SanTa/SanTa/ResultDetailScene/DetailHeader.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailLargerInfoView.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailSmallerInfoView.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailViewController.swift
  SanTa/SanTa/ResultScene/ResultUseCase.swift
Labels: Feature, Layout

#281 [Feat] 장소등록 화면, 사진허용 화면, 기록화면 Voiceover 적용
  SanTa/SanTa/MapScene/MapViewController.swift
  SanTa/SanTa/MountainAddingScene/MountainAddingView.swift
  SanTa/SanTa/MountainAddingScene/MountainAddingViewController.swift
  SanTa/SanTa/RecordingPhotoScene/RecordingPhotoViewController.swift
  SanTa/SanTa/RecordingScene/RecordingViewController+Extension.swift
  SanTa/SanTa/RecordingScene/RecordingViewController.swift
  SanTa/SanTa/ResultScene/RecordsViewCell.swift
  SanTa/SanTa/ResultScene/ResultViewController.swift
  SanTa/SanTa/ResultScene/ResultViewModel.swift
  SanTa/SanTa/ResultScene/SectionHeaderView.swift
  SanTa/SanTa/ResultScene/TotalRecordsViewCell.swift
Labels: Feature

#287 [Feature] 개별 기록 화면 상세 정보
  SanTa/SanTa/RecordingScene/Record.swift
  SanTa/SanTa/ResultDetailScene/DetailCell.swift
  SanTa/SanTa/ResultDetailScene/DetailHeader.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailLargerInfoView.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailModel.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailViewController.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailViewModel.swift
Labels: Feature

#283 [Refactor] 장소 등록 화면 리펙토링
  SanTa/SanTa/MapScene/MapViewCoordinator.swift
  SanTa/SanTa/MountainAddingScene/MountainAddingView.swift
  SanTa/SanTa/MountainAddingScene/MountainAddingViewController.swift
  SanTa/SanTa/MountainAddingScene/MountainAddingViewCoordinator.swift
  SanTa/SanTa/MountainAddingScene/MountainAddingViewModel.swift
Labels: Refactor

#292 [Feature] 기록 상세 화면 사진 섬네일 표시 및 모아보기 기능
  SanTa/SanTa.xcodeproj/project.pbxproj
  SanTa/SanTa/ResultDetailImagesScene/DetailImagesCell.swift
  SanTa/SanTa/ResultDetailImagesScene/ResultDetailImageViewCoordinator.swift
  SanTa/SanTa/ResultDetailImagesScene/ResultDetailImagesViewController.swift
  SanTa/SanTa/ResultDetailScene/DetailHeader.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailLargerInfoView.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailModel.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailViewController.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailViewCoordinator.swift
Labels: Feature, Layout, MapKit

#298 [Fix] 등록한 산의 고도 표기 수정
  SanTa/SanTa/MountainAddingScene/MountainAddingViewUseCase.swift
Labels: bug

#300 [Feat] Tracking Button 색상 변경
  SanTa/SanTa/MapScene/MapViewController.swift
Labels: Feature

#306 [Fix] 산 상세 화면 버그 수정
  SanTa/SanTa/MountainDetailScene/MountainDetailViewController.swift
  SanTa/SanTa/MountainDetailScene/MountainDetailViewCoordinator.swift
  SanTa/SanTa/MountainListScene/MountainListViewCoordinator.swift
Labels: bug

#310 [Feat] 설정 화면에서 사진 권한에 따른 분기처리
  SanTa/SanTa/SettingsScene/SettingsUsecase.swift
  SanTa/SanTa/SettingsScene/SettingsViewController.swift
  SanTa/SanTa/SettingsScene/SettingsViewModel.swift
Labels: Feature

#307 [Feature] 사진을 터치하면 해당 사진을 확대
  SanTa/SanTa.xcodeproj/project.pbxproj
  SanTa/SanTa/ResultDetailImagesScene/DetailImagesCell.swift
  SanTa/SanTa/ResultDetailImagesScene/ResultDetailImagesViewController.swift
  SanTa/SanTa/ResultDetailImagesScene/ResultDetailImagesViewCoordinator.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailViewController.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailViewCoordinator.swift
  SanTa/SanTa/ResultDetailScene/ThumbnailView.swift
  SanTa/SanTa/ResultDetailThumbnailScene/ResultDetailThumbnailViewController.swift
  SanTa/SanTa/ResultDetailThumbnailScene/ResultDetailThumbnailViewCoordinator.swift
Labels: Feature, Layout

#311 [Refactor] 상세 정보 셀 configure 리팩토링, 경사도 로직 수정
  SanTa/SanTa/ResultDetailScene/DetailCell.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailLargerInfoView.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailModel.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailViewController.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailViewModel.swift
Labels: bug, Refactor

#316 [Feat] 사진 썸네일 이미지 토글 기능
  SanTa/SanTa/ResultDetailScene/ResultDetailUseCase.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailViewController.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailViewModel.swift
Labels: Feature, MapKit

#317 [Fix] 고도차가 제대로 표기되지 않는 버그
  SanTa/SanTa/ResultScene/ResultViewModel.swift
Labels: bug

#330 [Fix] 산 상세 화면에서 고도에 단위가 표시되지 않는 버그 수정
  SanTa/SanTa/MountainListScene/MountainListViewController.swift
Labels: bug

#321 [Feature] 헤더뷰 정보 표시
  SanTa/SanTa.xcodeproj/project.pbxproj
  SanTa/SanTa/ResultDetailScene/DetailCell.swift
  SanTa/SanTa/ResultDetailScene/DetailHeader.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailLargerInfoView.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailModel.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailViewController.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailViewCoordinator.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailViewModel.swift
Labels: bug, Feature

#323 [Refactor] RecordingTitleViewController 리펙토링
  SanTa/SanTa/RecordingTitleScene/RecordingTitleViewCoordinator.swift
Labels: Refactor

#328 [Refactor] RecordingScene 리팩토링 및 예외 처리
  SanTa/SanTa/RecordingScene/RecordRepository.swift
  SanTa/SanTa/RecordingScene/RecordingModel.swift
  SanTa/SanTa/RecordingScene/RecordingUseCase.swift
  SanTa/SanTa/RecordingScene/RecordingViewController.swift
  SanTa/SanTa/RecordingScene/RecordingViewModel.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailModel.swift
Labels: bug, Refactor

#332 [Fix] 사진 모아보기 이미지
  SanTa/SanTa/ResultDetailScene/ResultDetailViewController.swift
Labels: bug

#334 [Fix] 기록화면 네비게이션 바
  SanTa/SanTa/ResultDetailScene/ResultDetailViewCoordinator.swift
Labels: bug

#335 [HOTFIX] 평균속도 이동거리 버그 수정
  SanTa/SanTa/ResultDetailScene/ResultDetailModel.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailViewModel.swift
Labels: bug

#337 [Feat] Locations 구조체 추가, 경사도 계산 로직 수정
  SanTa/SanTa.xcodeproj/project.pbxproj
  SanTa/SanTa/RecordingScene/Record.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailModel.swift
Labels: Feature

#342 [Fix] 기록 화면, 목록 화면 버그 해결
  SanTa/SanTa/MountainDetailScene/MountainDetailViewCoordinator.swift
  SanTa/SanTa/ResultScene/ResultViewController.swift
Labels: bug

#348 [REFACTOR] 기록화면 리펙토링 및 유닛 테스트
  SanTa/ResultSceneTests/ResultSceneTests.swift
  SanTa/SanTa.xcodeproj/project.pbxproj
  SanTa/SanTa.xcodeproj/xcshareddata/xcschemes/SanTa.xcscheme
  SanTa/SanTa/Persistences/CoreDataRecordStorage.swift
  SanTa/SanTa/ResultScene/ResultRepository.swift
  SanTa/SanTa/ResultScene/ResultUseCase.swift
  SanTa/SanTa/ResultScene/ResultViewModel.swift
Labels: Refactor

#353 [Refactor] ResultDetailView 사진 로직, RecordingViewModel UnitTest 추가
  SanTa/RecordingSceneTests/RecordingUseCaseTests.swift
  SanTa/RecordingSceneTests/RecordingViewModelTests.swift
  SanTa/SanTa.xcodeproj/project.pbxproj
  SanTa/SanTa/Application/AppDelegate.swift
  SanTa/SanTa/MountainListScene/MountainCell.swift
  SanTa/SanTa/RecordingScene/RecordingViewModel.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailViewController.swift
  SanTa/SanTa/ResultScene/ResultViewController.swift
  SanTa/SanTa/ResultScene/SectionHeaderView.swift
Labels: Refactor

#355 [Refactor] 빈 데이터 값에 대응하도록 자료구조 수정, 일부 계산로직 수정
  SanTa/SanTa/MountainDetailScene/MountainDetailViewController.swift
  SanTa/SanTa/MountainListScene/MountainListViewController.swift
  SanTa/SanTa/Persistences/CoreDataRecordStorage.swift
  SanTa/SanTa/RecordingScene/Record.swift
  SanTa/SanTa/Resources/SanTa.xcdatamodeld/SanTa.xcdatamodel/contents
  SanTa/SanTa/ResultDetailScene/ResultDetailModel.swift
  SanTa/SanTa/ResultDetailScene/ResultDetailViewModel.swift
  SanTa/SanTa/ResultScene/ResultViewModel.swift
Labels: bug, Refactor
