Repository boostcampwm-2021/iOS02-SanTa, pull requests merged in 2021-12, with the labels that each got.

#365 [Test] #363, #364 MapScene, MountainAddingScene 테스트 코드 작성
  SanTa/MapSceneTests/MapSceneTests.swift
  SanTa/MountainAddingSceneTests/MountainAddingSceneTests.swift
  SanTa/SanTa.xcodeproj/project.pbxproj
  SanTa/SanTa.xcodeproj/xcshareddata/xcschemes/SanTa.xcscheme
Labels: Test

#367 [Test] MountainList UnitTest
  SanTa/MountainListSceneTests/MountainListSceneTests.swift
  SanTa/RecordingSceneTests/RecordingUseCaseTests.swift
  SanTa/RecordingSceneTests/RecordingViewModelTests.swift
  SanTa/RecordingSceneTests/TestRecordingRepository.swift
  SanTa/SanTa.xcodeproj/project.pbxproj
  SanTa/SanTa.xcodeproj/xcshareddata/xcschemes/MountainListSceneTests.xcscheme
  SanTa/SanTa.xcodeproj/xcshareddata/xcschemes/SanTa.xcscheme
  SanTa/SanTa/Scenes/MountainListScene/MountainListViewRepository.swift
  SanTa/SanTa/Scenes/MountainListScene/MountainListViewUseCase.swift
Labels: Test

#366 [Test] 고도 테스트
  SanTa/ResultDetailAltitudeTest/ResultDetailAltitudeTest.swift
  SanTa/SanTa.xcodeproj/project.pbxproj
  SanTa/SanTa.xcodeproj/xcshareddata/xcschemes/SanTa.xcscheme
  SanTa/SanTa/Scenes/ResultDetailScene/ResultDetailModel.swift
Labels: Test

#369 [BUG] Pace 계산 로직 수정
  SanTa/SanTa/Scenes/ResultDetailScene/ResultDetailModel.swift
Labels: bug

#372 [Fix] 기록을 터치하였을 때 앱이 크래시나는 버그
  SanTa/SanTa/Scenes/ResultDetailScene/ResultDetailModel.swift
  SanTa/SanTa/Scenes/ResultDetailScene/ResultDetailViewModel.swift
Labels: bug

#376 [Fix] #375 음성 안내 로직 수정
  SanTa/SanTa/Scenes/RecordingScene/RecordingModel.swift
Labels: bug

#380 [BUG] 이동거리가 일치 하지 않는 문제 수정
  MountainGenerator/Extensions.swift
  MountainGenerator/GeoCoderResponse.swift
  MountainGenerator/MountainModel.swift
  MountainGenerator/main.swift
  SanTa/SanTa/Scenes/ResultDetailScene/ResultDetailModel.swift
Labels: bug

#379 [Docs] 산 데이터 추출 파일 추가
  MountainGenerator/Extensions.swift
  MountainGenerator/GeoCoderResponse.swift
  MountainGenerator/MountainModel.swift
  MountainGenerator/main.swift
Labels: Docs

#382 [Refactor] 기록정보 "-"로 화면 표시일 때 VoiceOver "없음" 으로 실행
  SanTa/SanTa/Scenes/ResultDetailScene/DetailCell.swift
  SanTa/SanTa/Scenes/ResultDetailScene/ResultDetailSmallerInfoView.swift
Labels: Refactor

#385 [Fix] 지도 화면에서 마커가 깜빡이는 버그 해결
  SanTa/SanTa/Scenes/MapScene/MountainAnnotationView.swift
Labels: bug
